// vue-components/container.vue
<template>
  <div class="container">
    <h3>This is a vue container</h3>
    <like-component 
      :nbLikes="nbLikes" 
      :id="currentId" 
      @addLike="addLike" 
      @removeLike="removeLike">
    </like-component>
  </div>
</template>

<script>
import LikeComponent from './like.vue';
import { LikeService } from '../services/like-service.js';

export default {
  name: 'Container',
  components: {
    LikeComponent
  },
  mounted() {
    this.likeService = new LikeService();
    this.updateLikes();
  },
  data: function() {
    return {
      currentId: 0,
      nbLikes: 0,
      likeService: {}
    }
  },
  methods: {
    updateLikes() {
      this.likeService.getVueLikes()
      .then(res => {
        this.nbLikes = res.data.length;
      });
    },
    addLike() {
      this.likeService.addVueLike(new Date().getTime())
        .then(res => {
          this.currentId = res.data.id;
          this.updateLikes();
        })
    },
    removeLike(id) {
      this.likeService.deleteVueLike(id)
        .then(() => {
          this.updateLikes();
        });
    }
  }
}
</script>

<style scoped>
  .container {
    border: 1px dashed yellowgreen;
    margin: 10px 0;
    padding: 10px 20px;
  } 
  h3 {
    color: yellowgreen;
  }
</style>

// react-components/container.js
import React, { Component } from 'react';
import { LikeComponent } from './like';
import { LikeService } from '../services/like-service';
import './style.css';

export class ReactContainer extends Component {
  constructor(props) {
    super(props);
    this.likeService = new LikeService();
    this.state = {
      nbLikes: 0,
    }
    this.addLike = this.addLike.bind(this);
    this.removeLike = this.removeLike.bind(this);
    this.updateLikeCount = this.updateLikeCount.bind(this);
  }

  componentDidMount() {
    this.updateLikeCount();
  }

  updateLikeCount() {
    this.likeService.getReactLikes()
      .then(res => {
        this.setState({
          nbLikes: res.data.length,
        })
      });
  }

  addLike() {
    return this.likeService.addReactLike(new Date().getTime())
      .then(res => {
        this.updateLikeCount();
        return res.data.id;
      });
  }

  removeLike(id) {
    this.likeService.deleteReactLike(id)
      .then(() => this.updateLikeCount());
  }

  render() {
    return (
      <div className="container">
        <h3>This is a react container</h3>
        <LikeComponent 
          nbLikes={this.state.nbLikes}
          addLike={this.addLike}
          removeLike={this.removeLike}
          >
        </LikeComponent>
      </div>
    )
  }
}
