// react-components/like.js
import React, { Component} from 'react';
import './style.css';

export class LikeComponent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      id: 0,
      isLiked: false,
    }
    this.onLikeHandler = this.onLikeHandler.bind(this);
  }

  onLikeHandler() {
    if (!this.state.isLiked) {
      this.props.addLike()
        .then(id => {
          this.setState({
            id: id
          })
        })
    } else {
      this.props.removeLike(this.state.id)
    }
    this.setState((prevState, props) => ({
      isLiked: !prevState.isLiked
    }))
  }

  render() {
    return (
      <div>
       <button 
        className="likeButton" 
        style={{
          color: this.state.isLiked ? 'blue' : 'black'
        }}
        onClick={this.onLikeHandler}>
          <i class="fas fa-heart"></i> {this.props.nbLikes}
        </button>
      </div>
    )
  }
}

// vue-components/like.vue
<template>
	<div>
		<button 
			@click="toggleLike()" 
			class="likeButton" 
			:class="{liked: isLiked}">
		  <i class="fas fa-heart"></i> {{nbLikes}}
		</button>
	</div>
</template>

<script>

export default {
	props: {
		nbLikes: {
			type: Number,
			default: 0,
		},
		id: {
			type: Number,
			default: 0,
		}
	},
	data: function() {
		return {
			isLiked: false,
		}
	},
	methods: {
		toggleLike() {
			if (!this.isLiked) {
				this.$emit('addLike')
			} else {
				this.$emit('removeLike', this.id)
			}
			this.isLiked = !this.isLiked;
		}
	}
}
</script>

<style scoped>
	.liked {
		color: yellowgreen;
	}
	.likeButton {
		font-size: 14px;
		padding: 10px;
		border-radius: 5px;
	}
</style>
